### ISSUE TITLE
Make markli self hosting

### ISSUE THREAD

**Issue by simonfxr** [lichtzeichner/markli#3]
For testing and showcasing markli, it should itself be a literate markdown file.
This is of course would lead to a bootstrapping problem, but its easy to provide a simple script to overcome that. The exctracted code files can still be commited to git, so users can still just install it by go get ....
A git pre-commit hook would need to ensure, that we don't commit stale extracted source files

**Comment by lichtzeichner** [comment]
I don't think that keeping the markli sources in a literate document provides any benefit. It only makes maintenance a bigger burden.

The intention of this project is to make it easy to document things like setup scripts for machines, not "full fledged" programs.
