### ISSUE TITLE
Make it possible to use multiple input files

### ISSUE THREAD

**Issue by simonfxr** [lichtzeichner/markli#6]
Markli should accept multiple occurrences of the -i/-input flag and process all files in order.
We should decide what should happen, when different input files reference the same output ###FILE pragmas. Probably we should treat it like one big input markdown file.

**Comment by lichtzeichner** [comment]
I implemented support for multiple `-i` flags. They're treated as one input, so multiple files referencing the same output just append to it. See examples and tests for more details.
